---
title: "Projekt Zespolowy HR"
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true
    default_style: "light"
    downcute_theme: "default"
---

```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
```

```{r}
library(dplyr)
library(readr)
HR=read.csv("HR.csv")
```
## Wstęp
### Usuwanie zbędnych kolumn
```{r}
HR <- HR %>% select(-EmployeeCount, -Over18, -StandardHours) 
```
### Wykrycie duplikatów
```{r}
duplikaty <- HR[duplicated(HR) | duplicated(HR, fromLast = TRUE), ]
```
### Wartośći brakujące
```{r}
library(naniar)
vis_miss(HR)
miss_var_summary(HR)
gg_miss_upset(HR)
gg_miss_var(HR)
```
Zmienną Attrition zmienimy na typ factor
```{r}
HR$Attrition <- factor(HR$Attrition, levels = c("No", "Yes"))
```
Imputacja danych
```{r}
library(mice)
HR_imputed <- mice(HR, m= 5, maxit = 50, seed = 500)
complete_data <- complete(HR_imputed)
```

```{r}
# Funkcja do identyfikacji odstających wartości (bazuje na IQR)
find_outliers <- function(x) {
  Q1 <- quantile(x, 0.25, na.rm = TRUE)
  Q3 <- quantile(x, 0.75, na.rm = TRUE)
  IQR <- Q3 - Q1
  lower_bound <- Q1 - 1.5 * IQR
  upper_bound <- Q3 + 1.5 * IQR
  which(x < lower_bound | x > upper_bound)
}

# Zidentyfikuj odstające wartości dla kolumn liczbowych
boxplot(complete_data$YearsAtCompany)
boxplot(complete_data$NumCompaniesWorked)
boxplot(complete_data$PerformanceRating)
boxplot(complete_data$StockOptionLevel)
boxplot(complete_data$TotalWorkingYears)
```

#Sprawdzenie struktury danych
```{r}
str(HR_cleaned)
```

#Wykreślanie mapy korelacji
```{r}
library(ggplot2)
library(reshape2)

mapa_cieplna <- melt(korelacje)
ggplot(data = mapa_cieplna, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0, limit = c(-1,1), space = "Lab", name="Korelacja") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1)) +
  coord_fixed()
```

#Nadgodziny a satysfakcja z pracy
```{r}
# Średnia satysfakcja z pracy
srednia_satysfakcja <- aggregate(JobSatisfaction ~ OverTime, data = HR_cleaned, FUN = mean)

head(srednia_satysfakcja)
```
```{r}
# Wykres słupkowy
ggplot(srednia_satysfakcja, aes(x = OverTime, y = JobSatisfaction, fill = OverTime)) +
  geom_bar(stat = "identity") +
  labs(title = "Średnia satysfakcja z pracy a nadgodziny",
       x = "Nadgodziny",
       y = "Średnia satysfakcja z pracy") +
  theme_minimal()
```

```{r}
# Wykres punktowy dla obu grup ze względu na zbliżony wynik
ggplot(HR_cleaned, aes(x = OverTime, y = JobSatisfaction, color = OverTime)) +
  geom_jitter(width = 0.2, alpha = 0.6) +
  labs(title = "Rozkład satysfakcji z pracy a nadgodziny",
       x = "Nadgodziny",
       y = "Satysfakcja z pracy") +
  theme_minimal()
```

#Stan cywilny a satysfakcja z pracy
```{r}
# Wykres pudełkowy
ggplot(HR_cleaned, aes(x = MaritalStatus, y = JobSatisfaction, fill = MaritalStatus)) +
  geom_boxplot() +
  labs(title = "Wpływ stanu cywilnego na satysfakcję z pracy",
       x = "Stan cywilny",
       y = "Satysfakcja z pracy") +
  theme_minimal()
```

```{r}
#Sprawdzenie danych ze względu na zbliżone wyniki
aggregate(JobSatisfaction ~ MaritalStatus, data = HR_cleaned, FUN = summary)

#Średnia dla każdej grupy (Divorced, Married, Single) jest zbliżona, co wskazuje na to, że status cywilny nie ma wpływu na satysfakcję z pracy. Może to sugerować, że inne czynniki, takie jak wynagrodzenie, mają większe znaczenie.
```



